CONTIKI_PROJECT = NN-gw dht_noise1 dht_noise2 mq131_env1 mq131_env2 multigas-client1 multigas-client2 PM10_1 PM10_2

all: $(CONTIKI_PROJECT)

##MODULES += os/services/shell

#CONTIKI_TARGET_SOURCEFILES += dht22.c multigas.c pm10-sensor.c adc-sensors.c
MAKE_NET = MAKE_NET_NULLNET
CONTIKI = ../..

include $(CONTIKI)/Makefile.include



