CONTIKI_PROJECT = coord.c beaconer sta sta1 sta2 sta3 sta4 sta5 sta6 sta7 

all: $(CONTIKI_PROJECT)

#MODULES += os/services/shell



CONTIKI=../..
MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include
