CONTIKI_PROJECT =  gw_dl_DB node_DBG
all: $(CONTIKI_PROJECT)

#MODULES += os/services/shell

#CONTIKI_TARGET_SOURCEFILES += dht22.c adc-sensors.c multigas.c pm10-sensor.c
 

CONTIKI = ../../..
MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include



